import "./globals.css";
import CommonAreas from './../components/AccessibilityCard/CommonAreas';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <meta name="description" content="Explore the most beautiful places to visit in 2025." />
      <meta name="keywords" content="travel, destinations, vacation, tourism" />
      <meta property="og:title" content="Best Travel Destinations 2025" />
      <meta property="og:description" content="Discover amazing places to travel this year." />
      <meta property="og:image" content="https://expedia.CommonAreas" />
      <body
        className={"antialiased"}
      >
        {children}
      </body>
    </html>
  );
}
